USE TUSKMANAGER;
CREATE TABLE UTENTE(
	EMAIL VARCHAR(80) PRIMARY KEY NOT NULL,
    PW VARCHAR(30) NOT NULL
);

CREATE TABLE WORKSPACE(
	ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NOME VARCHAR(30) NOT NULL
);

CREATE TABLE SCHEDA(
	TITOLO VARCHAR(30) NOT NULL,
    ID_WORKSPACE INT NOT NULL,
    FOREIGN KEY (ID_WORKSPACE) REFERENCES TUSKMANAGER.WORKSPACE(ID) ON DELETE CASCADE ON UPDATE CASCADE,
    PRIMARY KEY (TITOLO, ID_WORKSPACE)
);

CREATE TABLE COMPITO(
	TITOLO VARCHAR(30) NOT NULL,
    DESCRIZIONE VARCHAR(140),
    SCADENZA DATE,
    ID_WORKSPACE INT NOT NULL,
    TITOLO_SCHEDA VARCHAR(30) NOT NULL,
    FOREIGN KEY (ID_WORKSPACE) REFERENCES TUSKMANAGER.SCHEDA(ID_WORKSPACE) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (TITOLO_SCHEDA) REFERENCES TUSKMANAGER.SCHEDA(TITOLO) ON DELETE CASCADE ON UPDATE CASCADE,
    PRIMARY KEY(TITOLO,TITOLO_SCHEDA,ID_WORKSPACE)
);

CREATE TABLE RUOLO(
	NOME VARCHAR(30) PRIMARY KEY NOT NULL
);

CREATE TABLE GESTIONE(
	ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    TITOLO_COMPITO VARCHAR(30) NOT NULL,
    NOME_RUOLO VARCHAR(30) NOT NULL,
    FOREIGN KEY(TITOLO_COMPITO) REFERENCES TUSKMANAGER.COMPITO(TITOLO) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY(NOME_RUOLO) REFERENCES TUSKMANAGER.RUOLO(NOME) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE MEMBRO(
	ID_WORKSPACE INT NOT NULL,
    EMAIL_UTENTE VARCHAR(80) NOT NULL,
    NOME_RUOLO VARCHAR(30) NOT NULL,
    PRIMARY KEY(ID_WORKSPACE,EMAIL_UTENTE,NOME_RUOLO),
    FOREIGN KEY(NOME_RUOLO) REFERENCES TUSKMANAGER.RUOLO(NOME) ON DELETE NO ACTION ON UPDATE NO ACTION,
    FOREIGN KEY(ID_WORKSPACE) REFERENCES TUSKMANAGER.WORKSPACE(ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY(EMAIL_UTENTE) REFERENCES TUSKMANAGER.UTENTE(EMAIL) ON DELETE CASCADE ON UPDATE CASCADE
);

create user appTuskManager identified by "tricheco";
grant all privileges on *.* to appTuskManager;
